const games = [
  {
    title: "Cyberpunk 2077",
    description: "1 099₴",
    tags: ["RPG", "Action"],
    image: "./img/Cyberpunk.png",
    section: "popular",
    discount: "-25%",
    originalPrice: "1 999₴",
    inSlider: true,
  },
  {
    title: "Counter-Strike 2",
    description: "Безкоштовне",
    tags: ["Shooter", "Tactics", "Онлайн"],
    image: "./img/cs.png",
    section: "popular",
    inSlider: true,
  },
  {
    title: "Red Dead Redemption 2",
    description: "4 358₴",
    tags: ["Adventure", "Open world", "Western"],
    image: "./img/Red Dead Redemption 2.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "Dota 2",
    description: "Безкоштовне",
    tags: ["MOBA", "Multiplayer", "Онлайн"],
    image: "./img/Dota 2.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "R.E.P.O.",
    description: "225₴",
    tags: ["Adventure", "Horror", "Онлайн"],
    image: "./img/REPO.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "inZOI",
    description: "1 199₴",
    tags: ["Simulation", "Early Access"],
    image: "./img/inZOI.png",
    section: "new",
    inSlider: false,
  },
  {
    title: "Synergy",
    description: "391₴",
    tags: ["Strategy", "Simulation"],
    image: "./img/Synergy.png",
    section: "new",
    discount: "-24%",
    originalPrice: "515₴",
    inSlider: false,
  },
  {
    title: "DRIVE Rally",
    description: "209₴",
    tags: ["Simulation", "Racing"],
    image: "./img/DRIVE Rally.png",
    section: "new",
    inSlider: false,
  },
  {
    title: "The Witcher 3: Wild Hunt",
    description: "799₴",
    tags: ["RPG", "Adventure"],
    image: "./img/witcher3.png",
    section: "popular",
    inSlider: true,
  },
  {
    title: "Grand Theft Auto V",
    description: "999₴",
    tags: ["Action", "Adventure"],
    image: "./img/gta5.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "Among Us",
    description: "99₴",
    tags: ["Multiplayer", "Онлайн"],
    image: "./img/amongus.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "Apex Legends",
    description: "Безкоштовне",
    tags: ["Shooter", "Онлайн"],
    image: "./img/apexlegends.png",
    section: "popular",
    inSlider: false,
  },
  {
    title: "Minecraft",
    description: "499₴",
    tags: ["Simulation", "Adventure"],
    image: "./img/minecraft.png",
    section: "popular",
    inSlider: false,
  },
];